### ISSUE TITLE
Consider pre-generating the module file and test_version function

### ISSUE THREAD

**Issue by JordanAdams** [exercism/erlang#176] opened 2017-07-31 19:20 UTC
Having done a few tests so far, I'm starting to feel like creating the module file and defining the `test_version/0` function every time is kinda tedious. What I'm proposing is having a module file with the `test_version/0` function already implemented:

> src/foo.erl
```erlang
-module(foo).

-exports([test_version/0]).

% Your code goes here!

test_version() -> 2.
```

This also means we can ditch the check in `exercism.hrl` and avoid cryptic errors which mention an "example" module like this:

> **Uncaught exception!**
> exception error: undefined function example:steps/1

I'm more than happy do to the work if we think this'll be helpful 🙂

**Comment by JordanAdams** [comment] 2017-07-31 19:26
Just noticed #145 which I supposed covers this. Want me to jump on that?

**Comment by NobbZ** [comment] 2017-07-31 19:40
Yeah, I'd be really happy if you did it. I'll close this one as a duplicate of #145.

**Closed by NobbZ** 2017-07-31 19:40 UTC
